'''
This file contains all the constant variables
When adding variables, make sure to place them in an alphabetical order
'''
CAPTION = "Achtung Panzer"
EXPLOSION_SIZE = 65
EXPLOSION_SPEED = 8
FPS = 60
HEALTHBAR_SIZE = (0.5, 5)
MISSIL_LENGHT = 200
MISSIL_SIZE = 7
MISSIL_SPEED = 2
SOLID_OBJ_PUSHBACK = 0.02
MAP_BORDER_PUSHBACK = 0.05
SCREEN_SIZE = (1000, 700)
TANK_SPEED = 3
TANK_SPEED_BACK = 1.5
TANK_ACCELERATION = 0.125
TANK_ROTATION_SPEED = 2
TANK_HEIGHT = 50
TANK_WIDTH = 50
ANIMATION_SPEED = 2


MUSIC_CHANNELS = 1
MUSIC_DEFAULT_VOLUME = 0.40
GAMEFX_CHANNELS = (2, 3)
GAMEFX_DEFAULT_VOLUME = 0.40
MISCFX_CHANNELS = (4, 5)
MISCFX_DEFAULT_VOLUME = 0.40


DEAD_BUSH_SIZE = 80
STONE_MAX_SIZE = 180